// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class zmiana_Roli : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zmiana_Roli));
        
        string IMigrationMetadata.Id
        {
            get { return "202205221040408_zmiana_Roli"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
